// Generated by Melina.

import XCTest

final class MelinaUITests: XCTestCase {

    func testFirstScenario() {
        let app = launchApp([
            "experimet key":"experimet UCS home widget",
            "use_mock_server":"Hello",
        ])
        let label_1 = app.staticTexts["Label_2"].firstMatch
        waitForExistenceIfNeeded(label_1)
        XCTAssertFalse(label_1.isSelected)
        let view_2 = app.otherElements["View_2"].firstMatch
        waitForExistenceIfNeeded(view_2)
        XCTAssertEqual(view_2.value as? String, "Hello")
        let button_3 = app.buttons["Button 5555"].firstMatch
        waitForExistenceIfNeeded(button_3)
        button_3.tap()
        let textField_4 = app.textFields["Text 1"].firstMatch
        waitForExistenceIfNeeded(textField_4)
        textField_4.tap()
        textField_4.typeText("Hello world")
        self.loginInApp(app)
    }

}

fileprivate extension XCTestCase {
    func loginInApp(_ app: XCUIApplication) {
        let button_1 = app.buttons["Button 1"].firstMatch
        waitForExistenceIfNeeded(button_1)
        button_1.tap()
        let view_2 = app.otherElements["View_2"].firstMatch
        waitForExistenceIfNeeded(view_2)
        XCTAssertEqual(view_2.value as? String, "Hello")
    }
}

fileprivate extension XCTestCase {
    func launchApp(_ launchEnvironment: [String : String]) -> XCUIApplication {
        continueAfterFailure = false
        let app = XCUIApplication()
        app.launchEnvironment = launchEnvironment
        app.launch()
        return app
    }
}
fileprivate extension XCTestCase {
    func waitForExistenceIfNeeded(_ element: XCUIElement) {
        if !element.exists {
            XCTAssertTrue(element.waitForExistence(timeout: 5))
        }
    }
}
fileprivate extension XCTestCase {
    func waitForDisappear(_ element: XCUIElement) {
        let doesNotExistPredicate = NSPredicate(format: "exists == false")
        expectation(for: doesNotExistPredicate, evaluatedWith: element, handler: nil)
        waitForExpectations(timeout: 5) { error in
            if error != nil {
                XCTFail("The element did not disappear")
            }
        }
    }
}
